export const coachWebflowTemplate = {
  $schema: 'https://aredegalli.it/super-webflow/v1.0/template.schema.json',
  version: '1.0',
  id: 'coach-webflow-preview',
  name: 'Coach Webflow Preview',
  category: 'fitness',
  tags: ['coach', 'landing', 'custom-site'],
  author: 'coachly',
  theme: {
    id: 'coachly-dark',
    name: 'Coachly Dark',
    version: '1.0.0',
    colors: {
      primary: '#2563eb',
      primaryLight: '#60a5fa',
      primaryDark: '#1d4ed8',
      secondary: '#14b8a6',
      secondaryLight: '#5eead4',
      secondaryDark: '#0f766e',
      accent: '#f97316',
      accentLight: '#fdba74',
      background: '#0b1220',
      backgroundAlt: '#111827',
      surface: '#111827',
      surfaceAlt: '#1f2937',
      overlay: 'rgba(2,6,23,0.66)',
      text: '#f8fafc',
      textSecondary: '#cbd5e1',
      textMuted: '#94a3b8',
      textInverse: '#0b1220',
      textOnPrimary: '#ffffff',
      border: '#243043',
      borderStrong: '#324055',
      borderFocus: '#60a5fa',
      success: '#14b8a6',
      successLight: '#ccfbf1',
      warning: '#f59e0b',
      warningLight: '#fef3c7',
      danger: '#ef4444',
      dangerLight: '#fee2e2',
      info: '#38bdf8',
      infoLight: '#e0f2fe',
    },
    typography: {
      fonts: {
        heading: 'Poppins',
        body: 'Inter',
        mono: 'JetBrains Mono',
      },
      scale: {
        xs: 12,
        sm: 14,
        base: 16,
        lg: 18,
        xl: 20,
        '2xl': 24,
        '3xl': 30,
        '4xl': 36,
        '5xl': 48,
        '6xl': 60,
        '7xl': 72,
      },
    },
    shadows: {
      sm: { offsetX: 0, offsetY: 1, blur: 3, color: 'rgba(0,0,0,0.18)' },
      md: { offsetX: 0, offsetY: 6, blur: 18, color: 'rgba(0,0,0,0.25)' },
      lg: { offsetX: 0, offsetY: 12, blur: 32, color: 'rgba(0,0,0,0.35)' },
      xl: { offsetX: 0, offsetY: 20, blur: 48, color: 'rgba(0,0,0,0.45)' },
      inner: { offsetX: 0, offsetY: 2, blur: 4, color: 'rgba(0,0,0,0.2)', inset: true },
    },
    zIndex: { base: 0, raised: 10, sticky: 50, overlay: 100, modal: 200, popup: 300, tooltip: 400, max: 9999 },
  },
  meta: {
    title: '{{coach.fullName}} — custom website',
    description: 'Landing pubblico per coach con blocchi editoriali, CTA e proof.',
    ogImage: 'coach.avatar',
  },
  dataSchema: {
    'coach.fullName': { type: 'string', required: true, label: 'Nome coach', order: 1, group: 'Profilo' },
    'coach.tagline': { type: 'string', required: true, label: 'Tagline', order: 2, group: 'Profilo' },
    'coach.avatar': { type: 'image', required: true, label: 'Avatar', order: 3, group: 'Profilo' },
    'coach.bio': { type: 'richtext', required: true, label: 'Bio', order: 4, group: 'Profilo' },
    'coach.isPro': { type: 'boolean', required: false, default: false, label: 'Pro', order: 5, group: 'Profilo' },
    'coach.stats': {
      type: 'list',
      required: true,
      label: 'Stats',
      order: 6,
      group: 'Proof',
      validation: {
        itemSchema: {
          label: { type: 'string', required: true },
          value: { type: 'string', required: true },
        },
      },
    },
    'coach.services': {
      type: 'list',
      required: true,
      label: 'Services',
      order: 7,
      group: 'Services',
      validation: {
        itemSchema: {
          title: { type: 'string', required: true },
          description: { type: 'string', required: true },
        },
      },
    },
  },
  previewData: {
    coach: {
      fullName: 'Marta Riva',
      tagline: 'Performance coach per professionisti che vogliono progressi misurabili.',
      avatar: 'https://placehold.co/512x512',
      bio: 'Strength coach con focus su progressione, aderenza e risultati visibili.',
      isPro: true,
      stats: [
        { label: 'Clienti', value: '18 attivi' },
        { label: 'PR', value: '42 in 90 giorni' },
        { label: 'Rating', value: '4.9/5' },
      ],
      services: [
        { title: '1:1 coaching', description: 'Programmi personalizzati e check-in settimanali.' },
        { title: 'Online / hybrid', description: 'Sessioni in presenza o da remoto.' },
      ],
    },
  },
  pages: {
    home: {
      id: 'home-root',
      type: 'page-wrapper',
      props: { includeNavbar: true, includeFooter: true },
      style: { backgroundColor: 'background' },
      children: [
        {
          id: 'hero',
          type: 'section',
          style: { padding: [96, 40, 72, 40], backgroundOverlay: 'rgba(2,6,23,0.72)', minHeight: '100vh' },
          layout: { direction: 'column', alignItems: 'center', gap: 28 },
          children: [
            { id: 'avatar', type: 'avatar', props: { size: 128, shape: 'circle' }, data: { bindAttributes: { src: 'coach.avatar' } } },
            { id: 'name', type: 'heading', props: { level: 1 }, style: { fontSize: '5xl', fontFamily: 'heading', color: 'text', textAlign: 'center' }, data: { field: 'coach.fullName' } },
            { id: 'tagline', type: 'paragraph', style: { fontSize: 'xl', color: 'textSecondary', textAlign: 'center', maxWidth: 640 }, data: { field: 'coach.tagline' } },
            { id: 'cta', type: 'button', props: { label: 'Contatta il coach', variant: 'primary' } },
          ],
        },
        {
          id: 'stats',
          type: 'section',
          style: { padding: [64, 40], backgroundColor: 'surface' },
          layout: { direction: 'column', gap: 24 },
          children: [
            {
              id: 'stats-row',
              type: 'row',
              layout: { justifyContent: 'center', gap: 24, wrap: true },
              data: { listField: 'coach.stats', itemAlias: 'stat' },
              children: [
                {
                  id: 'stat-card',
                  type: 'service-card',
                  style: { maxWidth: 220 },
                  children: [
                    { id: 'stat-value', type: 'heading', props: { level: 3 }, data: { field: 'stat.value' } },
                    { id: 'stat-label', type: 'paragraph', data: { field: 'stat.label' } },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'services',
          type: 'section',
          style: { padding: [64, 40] },
          layout: { direction: 'column', gap: 20 },
          children: [
            { id: 'services-title', type: 'heading', props: { level: 2, text: 'Services' }, style: { fontSize: '3xl', fontFamily: 'heading' } },
            {
              id: 'services-row',
              type: 'row',
              layout: { gap: 20, wrap: true },
              data: { listField: 'coach.services', itemAlias: 'service' },
              children: [
                {
                  id: 'service-card',
                  type: 'service-card',
                  style: { maxWidth: 320 },
                  children: [
                    { id: 'service-title', type: 'heading', props: { level: 3 }, data: { field: 'service.title' } },
                    { id: 'service-desc', type: 'paragraph', data: { field: 'service.description' } },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
} as const;
